# CIE-IVI
IVI Project done under CIE

1. Had problems running repo on a system with Python 2.7

	use the command:
		```python3 /home/cie/bin/repo ...<br>
		python3 /home/cie/bin/repo init ...<br>```

	instead of:
		```repo init ...<br>```

3. Repo sync is failing<br>
	repo sync ran successfully until 93% completion.<br>

	Following errors occured thereafter:<br>
 	The complete error log can be inspected here: [repo_sync_error_log.txt](repo_sync_error_log.txt)<br>

  

## Log:- 
#### Week 1:-
- The host machine, crucial for our development environment, was equipped with Python 2.7, rendering the 'repo sync' command ineffective.
-  Faced with this obstacle, our team delved into the documentation to identify a solution. After thorough research and collaboration, we pinpointed the necessity to update the Python version to 3.8. Despite the initial setback, our team's collective effort and commitment prevailed as we successfully upgraded the Python version, ultimately enabling the 'repo sync' command to function seamlessly. This experience underscored the importance of adaptability and problem-solving skills, setting the tone for a collaborative and resilient project journey.


 
	
 ![image description](Screenshot%20from%202024-01-29%2015-49-07.png)
 ![image description](Screenshot%20from%202024-01-29%2015-49-15.png)
 ![image description](Screenshot%20from%202024-01-29%2015-49-22.png)
 ![image description](Screenshot%20from%202024-01-29%2015-49-30.png)
 ![image description](Screenshot%20from%202024-01-29%2015-49-40.png)
 
