# CIE-IVI
IVI Project done under CIE

Problems Faced:
1. Had problems running repo on a system with Python 2.7
    
    use the command:
      python3 /home/cie/bin/repo ...
    instead of:
      repo init ...
   
3. Repo sync is failing
    Solution is pending
